name: storytelling
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pygpu
  - mkl-service
  - pip
  - pip:
      - forbiddenfruit
      - azureml-defaults
      - scipy
      - nltk
      - sklearn
      - Cython
      - theano
      - nose
      - https://github.com/Lasagne/Lasagne/archive/master.zip
      - scikit-image
      - Pillow
      - azureml-sdk
      - gensim
      - opencv-python
